#!/usr/bin/env bash
set -Eeuo pipefail

# ============================================================
# TECO-CNP three-stage workflow
#
# Stage 1:
#   1934-1983 forcing, repeatedly cycled for C-N-P spin-up
#
# Stage 2:
#   1984-2021 historical simulation
#   Plant C pools QC(1:4) are replaced by low initial values.
#   Soil C pools QC(5:9) inherit the Stage-1 spin-up state.
#
# Stage 3:
#   2022-2024 P0, P25, P50 and P100 simulations
#   All treatments begin from the same end-of-2021 state.
# ============================================================

# ----------------------------
# 1. Directory settings
# ----------------------------

MAIN_DIR="$(
    cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
    pwd
)"

ROOT_DIR="$(
    cd "${MAIN_DIR}/.."
    pwd
)"

INPUT_DIR="${ROOT_DIR}/input"
OUTPUT_DIR="${ROOT_DIR}/output"

FORCING_DIR="${INPUT_DIR}/three_stage_forcing"

# Fortran always reads these two active files.
ACTIVE_FORCING="${INPUT_DIR}/TECO_forcing_active.txt"
ACTIVE_INITIAL="${INPUT_DIR}/Initialstate_heshan.csv"

# Low-carbon file: only QC(1:4) will be used.
LOW_C_INITIAL="${INPUT_DIR}/Initialstate_heshan zero.csv"

# Three forcing files generated by R.
STAGE1_FORCING="${FORCING_DIR}/TECO_阶段1_预热_1934_1983.txt"
STAGE2_FORCING="${FORCING_DIR}/TECO_阶段2_历史_1984_2021.txt"
STAGE3_FORCING="${FORCING_DIR}/TECO_阶段3_公共气象_2022_2024.txt"

# 50-year forcing × 100 cycles = approximately 5000 model years.
N_SPINUP="${N_SPINUP:-100}"

# Set to 1 while debugging; set to 0 after the model is stable.
DEBUG_BUILD="${DEBUG_BUILD:-1}"

# Set to 1 for the formal spin-up.
CHECK_CONVERGENCE="${CHECK_CONVERGENCE:-1}"

SPIN_REL_TOL="${SPIN_REL_TOL:-1e-4}"
SPIN_ABS_TOL="${SPIN_ABS_TOL:-1e-4}"

TIME_TAG="$(date +%Y%m%d_%H%M%S)"
RUN_DIR="${OUTPUT_DIR}/three_stage_${TIME_TAG}"
BACKUP_DIR="${RUN_DIR}/input_backup"
BUILD_DIR="${MAIN_DIR}/build_three_stage"

SPIN_OUTPUT="${OUTPUT_DIR}/NDSPINUP/teco_cnp"
SIM_OUTPUT="${OUTPUT_DIR}/sim/teco_cnp"

MODEL_EXE="${MAIN_DIR}/teco_cnp.exe"

mkdir -p \
    "${RUN_DIR}" \
    "${BACKUP_DIR}" \
    "${BUILD_DIR}" \
    "${OUTPUT_DIR}/NDSPINUP" \
    "${OUTPUT_DIR}/sim"

# ----------------------------
# 2. Basic functions
# ----------------------------

die() {
    echo "ERROR: $*" >&2
    exit 1
}

require_file() {
    [[ -s "$1" ]] || die "missing or empty file: $1"
}

show_log_and_die() {
    local message="$1"
    local logfile="$2"

    echo "ERROR: ${message}" >&2

    if [[ -f "${logfile}" ]]; then
        echo "Last 120 lines of ${logfile}:" >&2
        tail -n 120 "${logfile}" >&2
    fi

    exit 1
}

# ----------------------------
# 3. Check required source edits
# ----------------------------

require_file "${MAIN_DIR}/FileSize.f90"
require_file "${MAIN_DIR}/ParasModule.f90"
require_file "${MAIN_DIR}/SASpinUp.f90"
require_file "${MAIN_DIR}/TECO_CNP_main.f90"

if ! grep -Fq "TECO_forcing_active.txt" \
    "${MAIN_DIR}/ParasModule.f90"; then

    die "ParasModule.f90 is not reading TECO_forcing_active.txt"
fi

if grep -Eiq \
    'output_daily[[:space:]]*\([[:space:]]*(7|25)[[:space:]]*,' \
    "${MAIN_DIR}/SASpinUp.f90"; then

    die "SASpinUp.f90 still contains output_daily(7,:) or output_daily(25,:)"
fi

if grep -Eiq \
    'uni_Year[[:space:]]*\([[:space:]]*n_i_Year[[:space:]]*\)' \
    "${MAIN_DIR}/FileSize.f90"; then

    die "FileSize.f90 still contains the old uni_Year(n_i_Year) overflow"
fi

if ! grep -Eiq \
    'forcing_data[[:space:]]*\([[:space:]]*1[[:space:]]*,[[:space:]]*itime[[:space:]]*\)' \
    "${MAIN_DIR}/TECO_CNP_main.f90"; then

    die "TECO_CNP_main.f90 has not been updated to determine P-addition dates from forcing_data"
fi

# ----------------------------
# 4. Check input files
# ----------------------------

require_file "${ACTIVE_INITIAL}"
require_file "${LOW_C_INITIAL}"
require_file "${STAGE1_FORCING}"
require_file "${STAGE2_FORCING}"
require_file "${STAGE3_FORCING}"

# Validate initial-state files.
python3 - \
    "${ACTIVE_INITIAL}" \
    "${LOW_C_INITIAL}" <<'PY'
import csv
import math
import pathlib
import sys

normal_file = pathlib.Path(sys.argv[1])
low_file = pathlib.Path(sys.argv[2])


def read_initial(path):
    rows = []

    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.reader(handle):
            values = [
                value.strip()
                for value in row
                if value.strip()
            ]

            if values:
                rows.append([float(value) for value in values])

    if len(rows) != 3:
        raise SystemExit(
            f"{path} must contain exactly three non-empty rows."
        )

    if any(len(row) < 9 for row in rows):
        raise SystemExit(
            f"Each row in {path} must contain at least nine values."
        )

    rows = [row[:9] for row in rows]

    for row in rows:
        if not all(math.isfinite(value) for value in row):
            raise SystemExit(
                f"{path} contains NA, Inf or invalid values."
            )

    return rows


normal = read_initial(normal_file)
low = read_initial(low_file)

normal_c, normal_cn, normal_cp = normal
low_c = low[0]

if any(value <= 0 for value in normal_c):
    raise SystemExit(
        "The Stage-1 carbon pools must all be greater than zero."
    )

if any(value <= 0 for value in normal_cn):
    raise SystemExit(
        "The Stage-1 C:N ratios must all be greater than zero."
    )

if any(value <= 0 for value in normal_cp):
    raise SystemExit(
        "The Stage-1 C:P ratios must all be greater than zero."
    )

# Prevent the all-nine-pools-equal-to-one problem.
if sum(normal_c[4:9]) <= 10:
    raise SystemExit(
        "The soil C pools QC(5:9) in Initialstate_heshan.csv "
        "are too small. Restore the normal Stage-1 initial state."
    )

if any(value <= 0 for value in low_c[:4]):
    raise SystemExit(
        "QC(1:4) in Initialstate_heshan zero.csv "
        "must be small positive values, not zero."
    )

print("Initial-state files passed validation.")
print("Stage-1 soil C pool sum:", sum(normal_c[4:9]))
print("Stage-2 low plant C pools:", low_c[:4])
PY

# Validate forcing years and hourly counts.
python3 - \
    "${STAGE1_FORCING}" 1934 1983 \
    "${STAGE2_FORCING}" 1984 2021 \
    "${STAGE3_FORCING}" 2022 2024 <<'PY'
import collections
import datetime
import math
import pathlib
import sys


def leap(year):
    return (
        year % 400 == 0
        or (year % 4 == 0 and year % 100 != 0)
    )


def validate(path_string, first_year, last_year):
    path = pathlib.Path(path_string)
    counts = collections.Counter()
    day_hours = collections.defaultdict(list)
    rows = 0

    with path.open("r", encoding="utf-8-sig") as handle:
        header = handle.readline().strip().split()

        if len(header) < 11 or header[0].lower() != "year":
            raise SystemExit(
                f"Invalid TECO forcing header: {path}"
            )

        for line_number, line in enumerate(handle, start=2):
            if not line.strip():
                continue

            fields = line.split()

            if len(fields) < 11:
                raise SystemExit(
                    f"{path}, line {line_number}: "
                    "fewer than 11 columns."
                )

            try:
                values = [float(value) for value in fields[:11]]
            except ValueError:
                raise SystemExit(
                    f"{path}, line {line_number}: "
                    "non-numeric value."
                )

            if not all(math.isfinite(value) for value in values):
                raise SystemExit(
                    f"{path}, line {line_number}: "
                    "NA or Inf value."
                )

            year = int(values[0])
            doy = int(values[1])
            hour = int(values[2])

            counts[year] += 1
            day_hours[(year, doy)].append(hour)
            rows += 1

    expected_years = list(range(first_year, last_year + 1))

    if sorted(counts) != expected_years:
        raise SystemExit(
            f"{path}: expected years {first_year}-{last_year}, "
            f"but found {min(counts)}-{max(counts)}."
        )

    for year in expected_years:
        expected = (366 if leap(year) else 365) * 24

        if counts[year] != expected:
            raise SystemExit(
                f"{path}: year {year} contains "
                f"{counts[year]} rows; expected {expected}."
            )

    for (year, doy), hours in day_hours.items():
        if hours != list(range(1, 25)):
            raise SystemExit(
                f"{path}: {year} doy {doy} "
                "does not contain ordered hours 1-24."
            )

    expected_rows = sum(
        (366 if leap(year) else 365) * 24
        for year in expected_years
    )

    if rows != expected_rows:
        raise SystemExit(
            f"{path}: total rows {rows}; "
            f"expected {expected_rows}."
        )

    print(
        f"Forcing passed: {path.name}, "
        f"years={first_year}-{last_year}, rows={rows}"
    )


arguments = sys.argv[1:]

for index in range(0, len(arguments), 3):
    validate(
        arguments[index],
        int(arguments[index + 1]),
        int(arguments[index + 2]),
    )
PY

# ----------------------------
# 5. Preserve active inputs
# ----------------------------

cp -p \
    "${ACTIVE_INITIAL}" \
    "${BACKUP_DIR}/Initialstate_heshan_original.csv"

ACTIVE_FORCING_EXISTED=0

if [[ -e "${ACTIVE_FORCING}" ]]; then
    ACTIVE_FORCING_EXISTED=1

    cp -p \
        "${ACTIVE_FORCING}" \
        "${BACKUP_DIR}/TECO_forcing_active_original.txt"
fi

restore_inputs() {
    cp -f \
        "${BACKUP_DIR}/Initialstate_heshan_original.csv" \
        "${ACTIVE_INITIAL}"

    if [[ "${ACTIVE_FORCING_EXISTED}" -eq 1 ]]; then
        cp -f \
            "${BACKUP_DIR}/TECO_forcing_active_original.txt" \
            "${ACTIVE_FORCING}"
    else
        rm -f "${ACTIVE_FORCING}"
    fi
}

trap restore_inputs EXIT

# Stage-1 seed is the original normal initial state.
STAGE1_INITIAL="${BACKUP_DIR}/Initialstate_heshan_original.csv"

# ----------------------------
# 6. Compile TECO-CNP
# ----------------------------

echo "Compiling TECO-CNP..."

cd "${MAIN_DIR}"

if [[ "${DEBUG_BUILD}" -eq 1 ]]; then
    FFLAGS=(
        -O0
        -g
        -ffree-form
        -fcheck=all
        -fbacktrace
        -ffpe-trap=invalid,zero,overflow
    )
else
    FFLAGS=(
        -O2
        -ffree-form
    )
fi

SOURCES=(
    FileSize.f90
    ParasModule.f90
    SASpinUp.f90
    LIMITATION.f90
    NPUptakeDemand.f90
    NPDynamic.f90
    MCMC.f90
    TECO_CNP_main.f90
)

OBJECTS=()

for source_file in "${SOURCES[@]}"; do
    object_file="${BUILD_DIR}/${source_file%.f90}.o"

    gfortran \
        "${FFLAGS[@]}" \
        -J"${BUILD_DIR}" \
        -I"${BUILD_DIR}" \
        -c "${source_file}" \
        -o "${object_file}"

    OBJECTS+=("${object_file}")
done

gfortran \
    "${FFLAGS[@]}" \
    -o "${MODEL_EXE}" \
    "${OBJECTS[@]}" \
    -llapacke \
    -llapack \
    -lblas

require_file "${MODEL_EXE}"

echo "Compilation completed."

# ----------------------------
# 7. Run and output functions
# ----------------------------

prepare_output_directory() {
    local model_output="$1"
    local backup_label="$2"

    if [[ -d "${model_output}" ]]; then
        mv \
            "${model_output}" \
            "${RUN_DIR}/${backup_label}_preexisting"
    fi

    mkdir -p "${model_output}"
}

run_model() {
    local logfile="$1"
    shift

    echo "Command: ${MODEL_EXE} $*"

    if "${MODEL_EXE}" "$@" > "${logfile}" 2>&1; then
        :
    else
        local status=$?

        show_log_and_die \
            "TECO exited with status ${status}" \
            "${logfile}"
    fi

    # Some Fortran STOP statements return status zero.
    if grep -Eiq \
        'NSC is NA|gpp is nan|Fortran runtime error|Program received signal|SIGABRT|SIGSEGV|IEEE_INVALID_FLAG|IEEE_DIVIDE_BY_ZERO|IEEE_OVERFLOW_FLAG|out of range' \
        "${logfile}"; then

        show_log_and_die \
            "TECO reported a numerical or range error" \
            "${logfile}"
    fi
}

save_model_output() {
    local model_output="$1"
    local destination="$2"

    require_file \
        "${model_output}/teco_8cpools_cnp.csv"

    require_file \
        "${model_output}/CNP_Ncycle_simu_ratios_cnp.csv"

    require_file \
        "${model_output}/CNP_Pcycle_simu_ratios_cnp.csv"

    [[ ! -e "${destination}" ]] ||
        die "destination already exists: ${destination}"

    mv "${model_output}" "${destination}"
}

# ----------------------------
# 8. Create next-stage state
# ----------------------------

make_initial_state() {
    local result_dir="$1"
    local output_file="$2"
    local reset_plant="$3"

    python3 - \
        "${result_dir}" \
        "${output_file}" \
        "${reset_plant}" \
        "${LOW_C_INITIAL}" <<'PY'
import csv
import math
import pathlib
import sys

result_dir = pathlib.Path(sys.argv[1])
output_file = pathlib.Path(sys.argv[2])
reset_plant = int(sys.argv[3])
low_initial_file = pathlib.Path(sys.argv[4])

carbon_file = result_dir / "teco_8cpools_cnp.csv"
cn_file = result_dir / "CNP_Ncycle_simu_ratios_cnp.csv"
cp_file = result_dir / "CNP_Pcycle_simu_ratios_cnp.csv"


def last_row(path):
    last = None

    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.reader(handle):
            values = [
                value.strip()
                for value in row
                if value.strip()
            ]

            if values:
                last = [float(value) for value in values]

    if last is None or len(last) < 9:
        raise SystemExit(
            f"Cannot read nine values from {path}"
        )

    result = last[:9]

    if not all(math.isfinite(value) for value in result):
        raise SystemExit(
            f"Non-finite final state in {path}"
        )

    return result


def first_carbon_row(path):
    with path.open(
        "r",
        encoding="utf-8-sig",
        newline=""
    ) as handle:

        for row in csv.reader(handle):
            values = [
                value.strip()
                for value in row
                if value.strip()
            ]

            if values:
                result = [float(value) for value in values]

                if len(result) < 4:
                    raise SystemExit(
                        f"{path} contains fewer than four C pools."
                    )

                return result[:4]

    raise SystemExit(f"No data in {path}")


carbon = last_row(carbon_file)
cn_ratio = last_row(cn_file)
cp_ratio = last_row(cp_file)

if reset_plant == 1:
    low_plant_c = first_carbon_row(low_initial_file)

    if any(
        not math.isfinite(value) or value <= 0
        for value in low_plant_c
    ):
        raise SystemExit(
            "Low plant C pools must be finite and greater than zero."
        )

    # Replace only leaf, wood, root and reproductive/other plant C.
    carbon[0:4] = low_plant_c

if any(value <= 0 for value in carbon):
    raise SystemExit(
        "Generated carbon pools contain zero or negative values."
    )

if any(value <= 0 for value in cn_ratio):
    raise SystemExit(
        "Generated C:N ratios contain zero or negative values."
    )

if any(value <= 0 for value in cp_ratio):
    raise SystemExit(
        "Generated C:P ratios contain zero or negative values."
    )

output_file.parent.mkdir(
    parents=True,
    exist_ok=True,
)

with output_file.open(
    "w",
    encoding="utf-8",
    newline="\n",
) as handle:

    for values in (carbon, cn_ratio, cp_ratio):
        handle.write(
            ",".join(
                f"{value:.10g}"
                for value in values
            )
        )
        handle.write("\n")

print(f"Created state file: {output_file}")
print("Carbon pools:", carbon)
PY
}

# ----------------------------
# 9. Spin-up convergence check
# ----------------------------

check_spinup_convergence() {
    local result_dir="$1"

    python3 - \
        "${result_dir}" \
        "${SPIN_REL_TOL}" \
        "${SPIN_ABS_TOL}" <<'PY'
import csv
import math
import pathlib
import sys

result_dir = pathlib.Path(sys.argv[1])
relative_tolerance = float(sys.argv[2])
absolute_tolerance = float(sys.argv[3])

checks = {
    "C": (
        result_dir / "spinup_LoopVariables_cnp.csv",
        slice(4, 13),
    ),
    "N": (
        result_dir / "spinup_LoopVariablesNNN_cnp.csv",
        slice(0, 9),
    ),
    "P": (
        result_dir / "spinup_LoopVariablesPPP_cnp.csv",
        slice(0, 9),
    ),
}

failed = []

for element, (path, columns) in checks.items():
    if not path.exists() or path.stat().st_size == 0:
        raise SystemExit(
            f"Missing convergence file: {path}"
        )

    rows = []

    with path.open(
        "r",
        encoding="utf-8-sig",
        newline="",
    ) as handle:

        for row in csv.reader(handle):
            values = [
                value.strip()
                for value in row
                if value.strip()
            ]

            if values:
                rows.append(
                    [float(value) for value in values]
                )

    if len(rows) < 2:
        raise SystemExit(
            f"{path} contains fewer than two spin-up cycles."
        )

    previous = rows[-2][columns]
    current = rows[-1][columns]

    for pool, (old, new) in enumerate(
        zip(previous, current),
        start=1,
    ):
        if not math.isfinite(old) or not math.isfinite(new):
            failed.append(
                (element, pool, old, new, math.inf, 0)
            )
            continue

        scale = max(abs(old), abs(new), 1.0)

        threshold = (
            absolute_tolerance
            + relative_tolerance * scale
        )

        difference = abs(new - old)

        if difference > threshold:
            failed.append(
                (
                    element,
                    pool,
                    old,
                    new,
                    difference,
                    threshold,
                )
            )

if failed:
    print("Spin-up has not converged.")

    for item in failed[:40]:
        element, pool, old, new, difference, threshold = item

        print(
            f"{element} pool {pool}: "
            f"previous={old:.8g}, "
            f"current={new:.8g}, "
            f"difference={difference:.6g}, "
            f"threshold={threshold:.6g}"
        )

    raise SystemExit(
        "Increase N_SPINUP or inspect unstable pools."
    )

print("Spin-up convergence check passed.")
PY
}

# ============================================================
# 10. Stage 1: equilibrium spin-up
# ============================================================

echo "========================================"
echo "Stage 1: 1934-1983 equilibrium spin-up"
echo "Spin-up cycles: ${N_SPINUP}"
echo "========================================"

cp -f \
    "${STAGE1_FORCING}" \
    "${ACTIVE_FORCING}"

cp -f \
    "${STAGE1_INITIAL}" \
    "${ACTIVE_INITIAL}"

prepare_output_directory \
    "${SPIN_OUTPUT}" \
    "NDSPINUP"

run_model \
    "${RUN_DIR}/stage1_spinup.log" \
    1934 \
    1983 \
    3 \
    0 \
    1 \
    "${N_SPINUP}" \
    0 \
    0 \
    0

save_model_output \
    "${SPIN_OUTPUT}" \
    "${RUN_DIR}/stage1_spinup"

if [[ "${CHECK_CONVERGENCE}" -eq 1 ]]; then
    check_spinup_convergence \
        "${RUN_DIR}/stage1_spinup"
fi

# Construct the beginning-of-1984 state.
# QC(1:4) come from Initialstate_heshan zero.csv.
# QC(5:9), C:N and C:P come from the spin-up result.
STAGE2_INITIAL="${RUN_DIR}/Initialstate_stage2_1984.csv"

make_initial_state \
    "${RUN_DIR}/stage1_spinup" \
    "${STAGE2_INITIAL}" \
    1

# ============================================================
# 11. Stage 2: historical simulation
# ============================================================

echo "========================================"
echo "Stage 2: 1984-2021 historical simulation"
echo "========================================"

cp -f \
    "${STAGE2_FORCING}" \
    "${ACTIVE_FORCING}"

cp -f \
    "${STAGE2_INITIAL}" \
    "${ACTIVE_INITIAL}"

prepare_output_directory \
    "${SIM_OUTPUT}" \
    "stage2_sim"

run_model \
    "${RUN_DIR}/stage2_historical.log" \
    1984 \
    2021 \
    3 \
    0 \
    0 \
    1 \
    0 \
    0 \
    0

save_model_output \
    "${SIM_OUTPUT}" \
    "${RUN_DIR}/stage2_historical"

# Construct the common beginning-of-2022 state.
STAGE3_INITIAL="${RUN_DIR}/Initialstate_stage3_2022.csv"

make_initial_state \
    "${RUN_DIR}/stage2_historical" \
    "${STAGE3_INITIAL}" \
    0

# ============================================================
# 12. Stage 3: P-addition treatments
# ============================================================

echo "========================================"
echo "Stage 3: 2022-2024 P-addition treatments"
echo "========================================"

cp -f \
    "${STAGE3_FORCING}" \
    "${ACTIVE_FORCING}"

for P_RATE in 0 25 50 100; do

    echo "----------------------------------------"
    echo "Running P${P_RATE}"
    echo "----------------------------------------"

    # Ensure every treatment starts from the same 2022 state.
    cp -f \
        "${STAGE3_INITIAL}" \
        "${ACTIVE_INITIAL}"

    prepare_output_directory \
        "${SIM_OUTPUT}" \
        "stage3_P${P_RATE}"

    if [[ "${P_RATE}" -eq 0 ]]; then
        NP_ADDITION=0
    else
        NP_ADDITION=1
    fi

    run_model \
        "${RUN_DIR}/stage3_P${P_RATE}.log" \
        2022 \
        2024 \
        3 \
        0 \
        0 \
        1 \
        0 \
        "${NP_ADDITION}" \
        "${P_RATE}"

    save_model_output \
        "${SIM_OUTPUT}" \
        "${RUN_DIR}/stage3_P${P_RATE}"

done

echo "========================================"
echo "All three stages completed successfully."
echo "Results:"
echo "${RUN_DIR}"
echo "========================================"